### ISSUE TITLE
Feature request: API endpoint for retrieving favourite tags

### ISSUE THREAD

**Issue by Megalan** [imtbl/hyve#16]
Is it possible for you to make an api endpoint to get a list of favourite tags? I'm pretty close to the point where I have so much of them that I need some kind of a visual preview so I wanted to use your api to make a simple web app for that.
![screenshot](https://user-images.githubusercontent.com/942091/85952235-88c04880-b970-11ea-8653-07bb27e27897.png)

**Comment by imtbl** [comment]
Sorry, favorite tags are only a thing in hydrus client and not hydrus server. I generally only add things that can be done with both.

That said, hyve is pretty much in maintenance mode anyway now and I probably won't implement any new features in general.

I recommend you to make a hydrus feature request (<https://github.com/hydrusnetwork/hydrus/issues/>) to expose favorite tags via the client API (and maybe check out <https://github.com/floogulinc/hydrus-web>). For your intended use case of just viewing the favorite apps that's much better suited anyway, since you won't have all the overhead hyve comes with (its own DB copy that needs to be recreated every time you want to update data).
